# --- Animaciones ---
animations {
    enabled = yes
    # Animaciones fluidas pero con el "pop" del glitch
    bezier = sharpCurve, 0.05, 0.9, 0.1, 1.05
    bezier = fluidOut, 0.3, 0, 0.8, 0.15

    animation = windows, 1, 5, sharpCurve, popin 50%
    animation = windowsOut, 1, 4, fluidOut, popin 80%
    animation = border, 1, 10, default
    animation = fade, 1, 7, default
    animation = workspaces, 1, 5, sharpCurve, slide
}

# --- Window Rules ---
windowrule = match:class pavucontrol, float on
windowrule = match:class Bluetui, float on

# Reglas para Rofi (WiFi y menús)
windowrule = match:class rofi, opacity 0.85 0.85
layerrule = match:namespace ^(rofi)$, blur on
layerrule = match:namespace ^(rofi)$, ignore_alpha 0.5


# Reglas para el Centro de Control de SwayNC
layerrule = match:namespace ^(swaync-control-center)$, blur on
layerrule = match:namespace ^(swaync-control-center)$, ignore_alpha 0

# Reglas para las Notificaciones Flotantes de SwayNC
layerrule = match:namespace ^(swaync-notification-window)$, blur on
layerrule = match:namespace ^(swaync-notification-window)$, ignore_alpha 0
