# Hyprland Config

# --- Monitor ---
monitor=,preferred,auto,1

# --- Autostart ---
exec-once = dbus-update-activation-environment --systemd WAYLAND_DISPLAY XDG_CURRENT_DESKTOP
exec-once = systemctl --user import-environment WAYLAND_DISPLAY XDG_CURRENT_DESKTOP
exec-once = waybar
exec-once = swww-daemon
exec-once = waypaper --restore
exec-once = swaync
exec-once = sleep 1 && /usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1
exec-once = gnome-keyring-daemon --start --components=secrets
# --- Variables de Color ---
$sand = 0xffEFE9D9
$neonPink = 0xffFF52A2
$glitchTeal = 0xff00F5D4
$darkRed = 0xff880808
$darkRedInactive = 0xff2a1c1c
$darkPurple = 0xff6a1b9a
$darkPurpleInactive = 0xff1a1025
$bgBlur = 0x15EFE9D9

general {
    gaps_in = 5
    gaps_out = 15
    border_size = 2
    col.active_border = $darkPurple
    col.inactive_border = $darkPurpleInactive
    layout = dwindle
}



input {
    kb_layout = us
    follow_mouse = 1
    touchpad{
        disable_while_typing = false
    }
    
}


source = ~/.config/hypr/decorations.conf
source = ~/.config/hypr/animations.conf
source = ~/.config/hypr/keybinds.conf
