# Katarenai-Shell - Hyprland Config (Project Structure)

monitor=,preferred,auto,1

# Autostart: Apuntando a la configuración de Waybar
exec-once = waybar -c ~/.config/hypr/config.jsonc -s ~/.config/hypr/style.css

# Paleta Desert-Punk
$sand = rgb(EFE9D9)
$neonPink = rgb(FF52A2)
$glitchTeal = rgb(00F5D4)

general {
    gaps_in = 8
    gaps_out = 20
    border_size = 2
    col.active_border = $neonPink $glitchTeal 45deg
    col.inactive_border = rgba(EFE9D933)
    layout = dwindle
    # Estética de bordes rectos (README)
}

decoration {
    rounding = 0
    blur {
        enabled = true
        size = 12
        passes = 4
        new_optimizations = true
    }
    shadow {
        enabled = true
        range = 25
        render_power = 3
        color = rgba(00000044)
    }
}

animations {
    enabled = yes
    # Curva fluida con un ligero rebote (overshot) para vitalidad
    bezier = fluid, 0.05, 0.9, 0.1, 1.08
    bezier = snappy, 0.2, 1, 0.2, 1

    animation = windows, 1, 5, fluid, slide
    animation = windowsOut, 1, 4, snappy, popin 80%
    animation = border, 1, 10, default
    animation = fade, 1, 7, default
    animation = workspaces, 1, 6, fluid, slidevert
}

input {
    kb_layout = us
}

bind = SUPER, Q, killactive,
bind = SUPER, M, exit,
bind = SUPER, T, exec, alacritty

# Cambiar de escritorio
bind = SUPER, 1, workspace, 1
bind = SUPER, 2, workspace, 2
bind = SUPER, 3, workspace, 3
bind = SUPER, 4, workspace, 4
bind = SUPER, 5, workspace, 5
bind = SUPER, 6, workspace, 6
bind = SUPER, 7, workspace, 7
bind = SUPER, 8, workspace, 8
bind = SUPER, 9, workspace, 9
bind = SUPER, 0, workspace, 0

# Mover ventana a escritorio
bind = SUPER SHIFT, 1, movetoworkspace, 1
bind = SUPER SHIFT, 2, movetoworkspace, 2
bind = SUPER SHIFT, 3, movetoworkspace, 3
bind = SUPER SHIFT, 4, movetoworkspace, 4
bind = SUPER SHIFT, 5, movetoworkspace, 5
bind = SUPER SHIFT, 6, movetoworkspace, 6
bind = SUPER SHIFT, 7, movetoworkspace, 7
bind = SUPER SHIFT, 8, movetoworkspace, 8
bind = SUPER SHIFT, 9, movetoworkspace, 9
bind = SUPER SHIFT, 0, movetoworkspace, 0
bind = SUPER, B, exec, killall waybar; waybar -c ~/.config/hypr/config.jsonc -s ~/.config/hypr/style.css